### ISSUE TITLE
Error handling moving from Restsharp to Restsharp.Portable

### ISSUE THREAD

**Issue by jchannon** [FubarDevelopment/restsharp.portable#61] opened 2016-05-09 15:08 UTC
Hey guys, we are looking at moving from restsharp to restsharp portable, and we hit a snag where we currently check the `ErrorException` and `ErrorMessage` properties on `IRestResponse` in full restsharp and it's not there in portable at the moment, all we do is re-throw the exception if there is one.

                if (restResponse.ResponseStatus == ResponseStatus.Error || !string.IsNullOrEmpty(restResponse.ErrorMessage) || restResponse.ErrorException != null)
                {
                    var exToThrow = restResponse.ErrorException ?? new RestResponseErrorException(restResponse.ErrorMessage);

                    throw exToThrow;
                }

Is there any way to reproduce this functionality in restsharp.portable?

Thanks

**Comment by fubar-coder** [comment] 2016-05-09 15:22
Just a clarification before: RestSharp.Portable is different from RestSharp in its way to handle HTTP status codes. You have the following properties to control RestSharp.Portables behavior:

- `IRestClient.IgnoreResponseStatusCode`: When set to `true`, suppresses all exceptions caused by HTTP status codes (but not timeout exceptions)
- `IRestResponse.IsSucces`: Is `true` when the `StatusCode` doesn't indicate an error
- `StatusCode`, and `StatusDescription`: The raw status code, and its sent description

The default behavior is to throw exceptions when the HTTP status code indicates an error. You can enable a somewhat RestSharp compatible behavior by setting `IRestClient.IgnoreResponseStatusCode` to `true` and querying the respective properties of `IRestResponse` yourself.

Please close this issue when you feel that this question was sufficiently answered.

**Comment by jchannon** [comment] 2016-05-09 15:37
Hi,

Does that mean the advice is to try catch all client requests in case it
throws an exception?  So even if a Redirect of 302 occurs you throw an
exception because the IsSuccess is only true when statuscode < 300?

If you choose set IgnoreResponseStatusCode to true, the only way to
determine if an exception occurred is to check the statuscode?

Thanks

**Comment by fubar-coder** [comment] 2016-05-09 15:48
Redirects should be handled by `HttpClient`, or `HttpWebRequest` (without throwing exceptions), but otherwise: yes, all exceptions usually caused by HTTP status codes can be ignored by setting `IgnoreResponseStatusCode` to `true`, which is roughly equivalent to RestSharps behavior.

**Comment by fubar-coder** [comment] 2016-05-09 15:52
I'd suggest, that you create a small test application, to test if one of the configurations fit your needs. I usually keep `IgnoreResponseStatusCode` set to `false` and just catch all exceptions that might occur.

**Comment by jchannon** [comment] 2016-05-09 15:52
So if I get a 401 for example Restsharp.Portable will throw an exception?
Does that mean you have a custom exception per status code?

**Comment by fubar-coder** [comment] 2016-05-09 15:56
Strictly speaking, it's not RestSharp.Portable which throws the exception, but the underlying `HttpClient` or `HttpWebRequest`. The original RestSharp always catches the underlying exceptions and makes them available using the `ErrorException` property. RestSharp.Portable on the other side, usually passes all exceptions through to the caller, to avoid the need for error handling like you showed in your question.

**Comment by fubar-coder** [comment] 2016-05-13 12:08
Closing, because I guess that the question is answered :wink:

**Closed by fubar-coder** 2016-05-13 12:08 UTC
Labels: question
