### ISSUE TITLE
Restsharp Crashing WP app by throwing an exception that is not propagated to caller

### ISSUE THREAD

**Issue by maxpert** [FubarDevelopment/restsharp.portable#46] opened 2015-10-22 00:33 UTC
I have been receiving crashes due to RestSharp throwing an exception that can't be caught by me (some internal task barfing up?). I receive following Stack-trace whenever this happens.

```
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.
  at unknown location

Aggregated Exception [0]: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
   at Microsoft.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at RestSharp.Portable.RestClient.<Execute>d__10.MoveNext()
```

my code is pretty simple

```C#
try {
  await restSharpClient.Execute(request, cancellationToken);
} catch(Exception e) {
  // Exception should be caught here
}
```

Where cancellationToken is always CancellationToken.None, sending in a Token that is cancelled externally increases the number of crashes. Am I doing something wrong? Is there any flag? I have already set **IgnoreResponseStatusCode** flag to true already. There is a timeout of 60 seconds.

**Comment by fubar-coder** [comment] 2015-10-22 07:34
I'll take a look at it. Which version do you use?

**Comment by fubar-coder** [comment] 2015-10-22 08:17
Can you send me an example that allows me to reproduce this problem? The code you provided should work, but the library shouldn't produce a null reference exception either. Quite strange...

**Comment by maxpert** [comment] 2015-10-27 08:45
OK seems like I was doing something wrong I was reusing the existing connection (not disposing it) while previous request was already in progress (CancellationToken was CancellationToken.None). My external task was however cancelled (and on cancel it marked the RestSharpClient to be available for next usage). So it's something weird that I was doing, the reason I started passing None cancellation token was due to exceptions that I observed

```
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.
  at unknown location

Aggregated Exception [0]: System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.CancellationToken.ThrowIfCancellationRequested()
   at RestSharp.Portable.AsyncLock.<>c__DisplayClass2.<LockAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
``` 

So question I should be asking is, if I have done await on Execute with cancellation token and then due to external event if I dispose the connection instance, what would happen? I am pretty sure this time I am disposing off my connection object and issuing a cancellation on Token.

**Comment by fubar-coder** [comment] 2015-10-27 09:19
I'm not really sure what you mean when you talk about the "connection object", because RestSharp.Portable instantiates its own HttpRequestMessage which should open its own connection. You shouldn't dispose the connection instance. Instead, you should signal a cancellation though your cancellation token which you should pass through to the RestSharp.Portable request.

When you want to do multiple requests at once, you have to use multiple RestClient objects. This is unfortunately required due to a limitation of ```HttpClient```.

**Comment by maxpert** [comment] 2015-10-27 09:35
Let me explain, I have a connection pool of 16 (a slimsemaphore with count of 16). If somebody wants to do an HTTP request he request for a connection (which in-turn requires a lock on semaphore, hence only 16 objects will created at any time) and the pool returns a RestClient object for usage. The pool object is itself IDisposable. Here is exact code:

```c#
        public class PoolConnection : IDisposable
        {
            private readonly SemaphoreSlim releasePoolLock;

            public RestClient Client { get; private set; }

            public PoolConnection(RestClient c, SemaphoreSlim releasePoolLock)
            {
                this.Client = c;
                this.releasePoolLock = releasePoolLock;
            }

            public void Dispose()
            {
                this.releasePoolLock.Release();
                this.Client.Dispose();
            }
        }
```

Now the consumer of my PoolConnection can easily do 

```c#
using (PoolConnection connection = await transportPool.GetNext()){
    ...
    connection.Client.Execute(request, cancellationToken);
    ...
}
```

Now since cancellationToken is passed externally, it can be cancelled and it will be cancelled. From what you are describing, I should not be doing this.Client.Dispose(); in my PoolConnection class.

**Comment by fubar-coder** [comment] 2015-10-27 09:45
This code snippet looks fine. When you cancel the request with ```cancellationToken.Cancel()```, you get a ```TaskCancelledException``` or ```OperationCancelledException``` (base class of ```TaskCancelledException```). You should catch the later or the former (depending on your personal preferences - or even ```Exception```). You should also cancel the ```Execute``` and not some outer ```Task```, because this might kill the outer task before the ```Execute``` and therefore we have no outer code that is alive that is able to catch the exception (just an assumption, but it would explain the behavior).

**Comment by maxpert** [comment] 2015-11-08 09:40
OK So I did some further digging, and after going through code and looking at my scenario in detail this is what I think I know what might have happened. It's extremely hard to repro with a simple example app but in an application where there are multiple requests created and cancelled this might happen. Here is code for ```LockAsync```

```c#
        public Task<IDisposable> LockAsync(CancellationToken cancellationToken)
        {
#if PCL || SILVERLIGHT || NET40
            var wait = Task.Factory.StartNew(() =>
            {
                WaitHandle.WaitAny(new[] { _lock, cancellationToken.WaitHandle });
                cancellationToken.ThrowIfCancellationRequested();
            });
#else
            var wait = _lock.WaitAsync(cancellationToken);
#endif

            return wait.IsCompleted
                       ? _releaser
                       : wait.ContinueWith(
                           prevTask => _releaser.Result,
                           cancellationToken,
                           TaskContinuationOptions.ExecuteSynchronously,
                           TaskScheduler.Default);
        }
```
Now imagine a scenario when a token was cancelled and ```Task.Factory.StartNew``` has not started yet (unavailability of a free thread from thread-pool or being late in queue or anything!). Since the current task ```LockAsync``` has not been suspended it's quite possible the statement ```wait.ContinueWith``` part is executed. Now by the time the original task kicks in the continuation task has been cancelled, the ```ContinueWith``` will throw a OperationCancelledException and the wait task will cause exception being thrown with above stack trace. 

 I think the problem is passing the same cancellationToken to ContinueWith as used in wait task.

**Comment by fubar-coder** [comment] 2015-11-08 10:09
OK, thank you. I'll take a look at it.

**Comment by fubar-coder** [comment] 2015-11-08 22:26
There was a pull request #48 made by [evnik](https://github.com/evnik), which might fix your problem. You can try those changes in version 2.4.5. If this doesn't fix your problem, then please test again with 3.0.0-beta11, because it contains an assembly specifically for Windows Phone 8.1, which doesn't use the ```StartNew``` part of the code quoted above. Be aware that 3.0.0 contains many breaking changes, but they all should be quite easy to fix.

**Comment by maxpert** [comment] 2015-11-10 18:51
Well I did the fix and things seem to be working now :+1:

**Comment by fubar-coder** [comment] 2015-11-10 19:07
Oh, that was confusing, but good that is fixed now! :+1:

**Closed by fubar-coder** 2015-11-10 19:07 UTC
Labels: awaiting answer
